apiVersion: v1
kind: Secret
metadata:
  name: commonservicesv1-0-tls
  namespace: argocd
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdwVENDQlkyZ0F3SUJBZ0lRZXU0MVpVcDNk
    QVFJZjR4dEZNOTc0REFOQmdrcWhraUc5dzBCQVFzRkFEQ0IKdWpFTE1Ba0dBMVVFQmhNQ1ZWTXhG
    akFVQmdOVkJBb1REVVZ1ZEhKMWMzUXNJRWx1WXk0eEtEQW1CZ05WQkFzVApIMU5sWlNCM2QzY3Va
    VzUwY25WemRDNXVaWFF2YkdWbllXd3RkR1Z5YlhNeE9UQTNCZ05WQkFzVE1DaGpLU0F5Ck1ERXlJ
    RVZ1ZEhKMWMzUXNJRWx1WXk0Z0xTQm1iM0lnWVhWMGFHOXlhWHBsWkNCMWMyVWdiMjVzZVRFdU1D
    d0cKQTFVRUF4TWxSVzUwY25WemRDQkRaWEowYVdacFkyRjBhVzl1SUVGMWRHaHZjbWwwZVNBdElF
    d3hTekFlRncweQpOREF4TURneE1ETTROVGxhRncweU5UQXhNVGt4TURNNE5UZGFNSUdCTVFzd0NR
    WURWUVFHRXdKSlRqRVRNQkVHCkExVUVDQXdLUzJGeWJzU0JkR0ZyWVRFU01CQUdBMVVFQnhNSlFt
    RnVaMkZzYjNKbE1UTXdNUVlEVlFRS0V5cEIKYzJObGJuUWdRMjl1YzNWc2RHbHVaeUJUWlhKMmFX
    TmxjeUJRY21sMllYUmxJRXhwYldsMFpXUXhGREFTQmdOVgpCQU1NQ3lvdWMzUnZhSEp0TG1sdU1J
    SUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjFvUW1oOHZQNzFPK2li
    SlFHS0pRZjBmbHBBTXJKWlVvQ1lGOSs1UzRiZ3lIcWJJN0lPcGxVRmZ0TGx6SVZ3eXQKU1RWOEQz
    ZWQxc25IVlRkVWloS1RpNTNJWWRrMVNmczByWGhsK1o2VXR4UE80RFlmZy9mbmhBVE1tNU4wbDB6
    bQpwZkQvNE9uQzI1MDU5U2t2ODBLZm1scVVXUmpmZmNrMjlQZWQrN1IreWhpYnJvUE92T0NGWjRP
    NDREWVhiNC9kClBYM0k3RjZzajQxa2M3cEtsNytpek9KOGdiZitpYUxMVU9OeWhnWmlQTDN3djNr
    OWNObFIvazd5djRzbm84ZlgKS0I4TDVhb3pTc0VPOENDNlJabGxvWGlRemlwOUlRZXE1ODI4NWRK
    YWVEa3VPVkM4TVVKamFjMjFPMkl1d2lDeQoyeGhLT0NiMGVlSUlVZWk2RWRXUkl3SURBUUFCbzRJ
    QzNEQ0NBdGd3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVdjNGZVdaSXFJNHJQY1dJ
    VndEMmdhb04raDlnd0h3WURWUjBqQkJnd0ZvQVVncUp3ZE4yOFV6L1AKZTlUM3pYK25ZTVlLVEw4
    d2FBWUlLd1lCQlFVSEFRRUVYREJhTUNNR0NDc0dBUVVGQnpBQmhoZG9kSFJ3T2k4dgpiMk56Y0M1
    bGJuUnlkWE4wTG01bGREQXpCZ2dyQmdFRkJRY3dBb1luYUhSMGNEb3ZMMkZwWVM1bGJuUnlkWE4w
    CkxtNWxkQzlzTVdzdFkyaGhhVzR5TlRZdVkyVnlNRE1HQTFVZEh3UXNNQ293S0tBbW9DU0dJbWgw
    ZEhBNkx5OWoKY213dVpXNTBjblZ6ZEM1dVpYUXZiR1YyWld3eGF5NWpjbXd3SVFZRFZSMFJCQm93
    R0lJTEtpNXpkRzlvY20wdQphVzZDQ1hOMGIyaHliUzVwYmpBT0JnTlZIUThCQWY4RUJBTUNCYUF3
    SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVICkF3RUdDQ3NHQVFVRkJ3TUNNQk1HQTFVZElBUU1NQW93
    Q0FZR1o0RU1BUUlDTUlJQmdBWUtLd1lCQkFIV2VRSUUKQWdTQ0FYQUVnZ0ZzQVdvQWR3RG0wakZq
    UUhlTXdSQkJCdGR4dWM3QjBrRDJsb1NHKzdxSE1oMzlIamVPVUFBQQpBWXpvcDNyTEFBQUVBd0JJ
    TUVZQ0lRRFhSdXVpWFRwb1lkdnBJaWpBdWM1aXpPbWYrVEVpWkNHdTNBSlFudGZxCkRnSWhBSzRt
    bXFvWXRmSTh4di9hV3JSN2MwcWpYMFl6bkY0VTRyY05ITlRaOEZuUEFIWUFQeGRMVDljaVIxaVUK
    SFdVY2hMNE5FdTJRTjM4ZmhXcnJ3YjhvaGV6NFpHNEFBQUdNNktkNitBQUFCQU1BUnpCRkFpQXov
    ZGNjWVVMTApUUFBOeXZnalh2OSs0UE53dXl3VWVDeStTQjNjZnVYbTlRSWhBTUFXNUs1L0JYSkRV
    d2ZpdzdZWTVzM2VnUzdLClcyZG1LWCsxd3dVWGJ0ZWNBSGNBVG5XakoxeWFFTU00VzJ6VTN6OVM2
    eDN3NEk0YmpXbkFzZnBrc1dLYU9kOEEKQUFHTTZLZDdIZ0FBQkFNQVNEQkdBaUVBaEJLQjU4djB4
    SzMrR3VUbnpCWjFvWFZXanJqY1FuRFRZVFNNbFpBaApHSU1DSVFET2p0U1I1czdTcVlBOHo1ZU1j
    VnAxbnF1M3ZRYkZKNCtjNFNucUZjVTZlekFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQVRBNjNL
    bXh1VHc3SHM5Mk4wSzdhdlk3cEZGZmQ5WXJWOHRwYWRlSmdEQStYS3YrSXhhakYKTzlvVzZ4Q3pv
    Yk04Ung2eUtnWDlyM1dYd003dTVjRStKZnZDbWxYOC9UVWg4UkxiMFZ3TXA1NmxrY2VEbDBIOAow
    eEFtRjhDQVNtRE1RODF2MHNPdVdndldZYkJUS2NqNzlKeC9qUlJNbEFUTlZ2QTBQNlR1RGlhcEtZ
    RUU3UkM3CnVZTWJ4NEljSlBockl1aVpXbGZTNzcrNlMydW45MnlpcmtvS3A2Z3RvQW5CbXRvTU1L
    ZFJFNWVkb2JqdkVyVmgKN0ppeTNmbnRMNlBKNWVYb1JBdmQ1SjkxZTRrNnFGa1VIN0RyYjRPNUU4
    TXFDUFd2RGgrWHFhRk9vRXBHVnA1SgpEaUEyZ2dQa1NxODBJdTJTYmhNeUdCWmJHWVU0aHpaekRB
    PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
    TUlJRkRqQ0NBL2FnQXdJQkFnSU1EdWxNd3dBQUFBQlIwM2VGTUEwR0NTcUdTSWIzRFFFQkN3VUFN
    SUcrTVFzdwpDUVlEVlFRR0V3SlZVekVXTUJRR0ExVUVDaE1OUlc1MGNuVnpkQ3dnU1c1akxqRW9N
    Q1lHQTFVRUN4TWZVMlZsCklIZDNkeTVsYm5SeWRYTjBMbTVsZEM5c1pXZGhiQzEwWlhKdGN6RTVN
    RGNHQTFVRUN4TXdLR01wSURJd01Ea2cKUlc1MGNuVnpkQ3dnU1c1akxpQXRJR1p2Y2lCaGRYUm9i
    M0pwZW1Wa0lIVnpaU0J2Ym14NU1USXdNQVlEVlFRRApFeWxGYm5SeWRYTjBJRkp2YjNRZ1EyVnlk
    R2xtYVdOaGRHbHZiaUJCZFhSb2IzSnBkSGtnTFNCSE1qQWVGdzB4Ck5URXdNRFV4T1RFek5UWmFG
    dzB6TURFeU1EVXhPVFF6TlRaYU1JRzZNUXN3Q1FZRFZRUUdFd0pWVXpFV01CUUcKQTFVRUNoTU5S
    VzUwY25WemRDd2dTVzVqTGpFb01DWUdBMVVFQ3hNZlUyVmxJSGQzZHk1bGJuUnlkWE4wTG01bApk
    QzlzWldkaGJDMTBaWEp0Y3pFNU1EY0dBMVVFQ3hNd0tHTXBJREl3TVRJZ1JXNTBjblZ6ZEN3Z1NX
    NWpMaUF0CklHWnZjaUJoZFhSb2IzSnBlbVZrSUhWelpTQnZibXg1TVM0d0xBWURWUVFERXlWRmJu
    UnlkWE4wSUVObGNuUnAKWm1sallYUnBiMjRnUVhWMGFHOXlhWFI1SUMwZ1RERkxNSUlCSWpBTkJn
    a3Foa2lHOXcwQkFRRUZBQU9DQVE4QQpNSUlCQ2dLQ0FRRUEyaitXMEUyNUwwVG4yemxlbTFEdVhL
    Vmgya0ZuVXdtcUFKcU9WMzhwYTl2SDRTRWtxanJRCmpVY2owdTF5RnZDUklkSmR0N2hMcUlPUHQ1
    RXlhTS9PSlpNc3NuMlh5UDdCdEJlNkNaNERrSk43ZkVtREltaUsKbTk1SHd6R1llaTU5UUF2Uzd6
    N1Rzb3lxajBpcC93RG9LVmdHOTdhVFdwUnpKaWF0V0E3bFFyalY2bk41WkdoVApKYmlFejVSNnJn
    WkZES05yVGRER3Z1b1lwRGJ3a3JLNkhJaVBPbEovOTE1dGd4eWQ4Qi9sdzliZHBYaVNQYkJ0CkxP
    ckp6NVJCR1hGRWFMcEhQQVRwWGJvKzhEWDNGYmFlOGk0VkhqOUh5TWc0cDNORlhVMndPN0dPRnlr
    MzZ0MEYKQVNLN2xEWXFqVnMxL2xNWkx3aEd3U3F6R21JZFRpdlpHd0lEQVFBQm80SUJERENDQVFn
    d0RnWURWUjBQQVFILwpCQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdNd1lJS3dZ
    QkJRVUhBUUVFSnpBbE1DTUdDQ3NHCkFRVUZCekFCaGhkb2RIUndPaTh2YjJOemNDNWxiblJ5ZFhO
    MExtNWxkREF3QmdOVkhSOEVLVEFuTUNXZ0k2QWgKaGg5b2RIUndPaTh2WTNKc0xtVnVkSEoxYzNR
    dWJtVjBMMmN5WTJFdVkzSnNNRHNHQTFVZElBUTBNREl3TUFZRQpWUjBnQURBb01DWUdDQ3NHQVFV
    RkJ3SUJGaHBvZEhSd09pOHZkM2QzTG1WdWRISjFjM1F1Ym1WMEwzSndZVEFkCkJnTlZIUTRFRmdR
    VWdxSndkTjI4VXovUGU5VDN6WCtuWU1ZS1RMOHdId1lEVlIwakJCZ3dGb0FVYW5JbWV0QWUKNzMz
    bk8ybFIxR3lObjVBU1pxc3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRG5WanBpRFljZ3NZOU53
    SFJrdwp5L1lKck14cDFjbmNOMEh5TWcvdmRNTlk5bmduQ1RRSWxaSXYxOSs0by8wT2dlbWtuTk0v
    VFdnckZURUtGY3hTCkJKUG9rMUREMmJIaTRXaTNPZ2wwOFRSWUNqOTNtRUM0NW1qL1hlVElSc1hz
    Z2RmSmdoaGNnODV4Mkx5L3JKa0MKazl1VW1JVFNuS2ExL2x5NzhFcXZJYXpDUDBra1o5WXVqcytz
    ekdRVkdITGxiSGZUVXFpNTNZMnNBRW8xR2RSdgpjNk4xNzJ0a3crQ05neEtoaXVjT2hrM1l0Q0Fi
    dm1xbGpFdG9adU1yeDFnTCsxWVExSkg3SGRNeFdCQ01ST04xCmV4Q2R0VGl4OXFyS2dXUnM2UExp
    Z1ZXWFVYL2h3aWRRb3NrOFd3QkQ5bHU1MWFYOC93ZFFRR2NIc0ZYd3QzNXUKTGN3PQotLS0tLUVO
    RCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFUGpDQ0F5
    YWdBd0lCQWdJRVNsT01LREFOQmdrcWhraUc5dzBCQVFzRkFEQ0J2akVMTUFrR0ExVUVCaE1DClZW
    TXhGakFVQmdOVkJBb1REVVZ1ZEhKMWMzUXNJRWx1WXk0eEtEQW1CZ05WQkFzVEgxTmxaU0IzZDNj
    dVpXNTAKY25WemRDNXVaWFF2YkdWbllXd3RkR1Z5YlhNeE9UQTNCZ05WQkFzVE1DaGpLU0F5TURB
    NUlFVnVkSEoxYzNRcwpJRWx1WXk0Z0xTQm1iM0lnWVhWMGFHOXlhWHBsWkNCMWMyVWdiMjVzZVRF
    eU1EQUdBMVVFQXhNcFJXNTBjblZ6CmRDQlNiMjkwSUVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5
    eWFYUjVJQzBnUnpJd0hoY05NRGt3TnpBM01UY3kKTlRVMFdoY05NekF4TWpBM01UYzFOVFUwV2pD
    QnZqRUxNQWtHQTFVRUJoTUNWVk14RmpBVUJnTlZCQW9URFVWdQpkSEoxYzNRc0lFbHVZeTR4S0RB
    bUJnTlZCQXNUSDFObFpTQjNkM2N1Wlc1MGNuVnpkQzV1WlhRdmJHVm5ZV3d0CmRHVnliWE14T1RB
    M0JnTlZCQXNUTUNoaktTQXlNREE1SUVWdWRISjFjM1FzSUVsdVl5NGdMU0JtYjNJZ1lYVjAKYUc5
    eWFYcGxaQ0IxYzJVZ2IyNXNlVEV5TURBR0ExVUVBeE1wUlc1MGNuVnpkQ0JTYjI5MElFTmxjblJw
    Wm1sagpZWFJwYjI0Z1FYVjBhRzl5YVhSNUlDMGdSekl3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVB
    QTRJQkR3QXdnZ0VLCkFvSUJBUUM2aExaeTI1NE1hK0taNlRBQnAzYnFNcmlWUVJySjJtRk9XSExQ
    L3ZhQ2ViOXpZUVlLcFNmWXMxL1QKUlU0Y2N0Wk9Ndkp5aWcvM2d4blFhb0NBQUVVZXNNZm5tcjhT
    VnljY28yZ3ZDb2U5YW1zT1htWHpISGZWMUlXTgpjQ0cwc3pMbmk2TFZoamtDc2JqU1I4N2t5VW5F
    TzZmZSsxUjlWNzd3Nkc3Q2ViSTZDMVhpVUpnV01oTmNMM2hXCndjS1VzL0phNUNlYW55VFh4dXpR
    bXlXQzQ4ekN4RVhGakpkNkJtc3FFWitwQ201SU8yL2IxQkVaUXZlUEI3LzEKVTErY1B2UVhMT1pw
    ckU0eVRHSjM2cmZvNWJzMHZCbUxycHhSNTdkK3RWT3hNeUxsYmM5d1BCcjY0cHRudG9QMApqYVd2
    WWt4TjRGaXNaRFFTQS9pMmpaUmpKS1J4QWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUJC
    akFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJScWNpWjYwQjd2ZmVjN2FWSFVi
    STJma0JKbXF6QU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZVo4ZGxzYTJlVDhpallmVGh3TUVZ
    R3BybWk1WmlYTVJyRVBSOVJQLwpqVGtyd1BLOVQzQ01xUy9xRjhRTFZKN1VHNWFZTXp5b3JXS2lB
    SGFyV1dsdUJoMSt4TGxFalppdkV0Umgyd29aClJrZno2L2Rqd1VBRlFLWFN0L1MxbWphL3FZaDJp
    QVJWQkN1Y2gzOGFOengrTGFVYTJOU0pYc3E5ckQxczJHMnYKMWZOMkQ4MDdpRGdpbld5VG1zUTl2
    NEliWlQrbUQxMnEvT1d5RmNxMXJjYThQZENFNk9vR2NyQk5PVEo0dno0UgpuQXVrblpvaDgvQ2JD
    ekI0MjhIY2gwUCt2R09heXNYQ0hNbkhqZjg3RWxnSTVyWTk3SG9zVHZ1RGxzNE1QR21IClZIT2tj
    OEtULzFFUXJCVlVBZGo4QmJHSm9YOTBnNXBKMTl4T2U0cEliNHRGOWc9PQotLS0tLUVORCBDRVJU
    SUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktrd2dnU2xBZ0VBQW9JQkFRRFdoQ2FIeTgvdlU3NkoKc2xBWW9sQi9SK1drQXlzbGxTZ0pn
    WDM3bExodURJZXBzanNnNm1WUVYrMHVYTWhYREsxSk5Yd1BkNTNXeWNkVgpOMVNLRXBPTG5jaGgy
    VFZKK3pTdGVHWDVucFMzRTg3Z05oK0Q5K2VFQk15YmszU1hUT2FsOFAvZzZjTGJuVG4xCktTL3pR
    cCthV3BSWkdOOTl5VGIwOTUzN3RIN0tHSnV1Zzg2ODRJVm5nN2pnTmhkdmo5MDlmY2pzWHF5UGpX
    UnoKdWtxWHY2TE00bnlCdC82Sm9zdFE0M0tHQm1JOHZmQy9lVDF3MlZIK1R2Sy9peWVqeDljb0h3
    dmxxak5Ld1E3dwpJTHBGbVdXaGVKRE9LbjBoQjZybnpiemwwbHA0T1M0NVVMd3hRbU5wemJVN1lp
    N0NJTExiR0VvNEp2UjU0Z2hSCjZMb1IxWkVqQWdNQkFBRUNnZ0VCQU1rdk4xTzBlbGRpbXhoWSsz
    V2ZCUS9hUmkwRUs3c2JvR2tKNFRYSnpRNnAKQWJMTlRWY1pmZHRVRzBXWUR1eFZIMC9Cc1pCd0Jz
    QWlqYWdHTkdzcDhPYklHOTVvNytscWg0VUpuZG4yT0ZOYgphSEl2VUc5Y1dPMGY4eVVWcmdzWVBG
    ajFKWVd5dHVWeEY2SXQ5cUtXb1VrS0dvZFZKSVc3NktibWRHeFVZM1QwCjFyYktJa00xditWa2hN
    dTI3Ymt0dTI3UnUyN3BzYXNON1FEcnVpaWxRb1J6dlR2WXJweHZUM3pIZlY1K0RmSXAKL0F4OFhJ
    OHpUdzRNQzhVS2FKMHhETXQ1K1psdFBwaFJaZFROYW1XTmdoZmNNbmtNQ0lNOE9KTDBkUkJ1ajdz
    eQpvTW1RWmN2UjdTSUNrM2NYSkNSUWsvMUNETjhWV05ERzBlazdFYkdweThFQ2dZRUErdWVOVHRZ
    VS9CSW9wZGVOCjRVcTFSbmxNVC9JazUxcE5uWjI0bFg5ekt4eHpEMmZCOFIrN0NmZWhseGZ4eHBV
    b201OXpSb0lDTGV5Wml6MzMKelE2YUxYbWNLS2QwcStTM1BSM0puU1YrYVNXM2pIQ00vMkU3M1g3
    TUlUSUtkRnIyUk9ySEtjTC9FcnM5UE9xNApGNGM2dTZZZ0RsUjNvOHd6NWR1eW5GQ2ViKzhDZ1lF
    QTJ0OXFuZFdSZzBvVE9nU0NoUzNuRUptT0YvcTBRTitOCkM5amVnaUZEcUdWNHlEdjA0RDVNTXg3
    WjJ3RlhrRG1QVjZGbmhhbVJhS01CYndneWdGNmdSc1NrSHNXeHZ6aGoKdWIwUmdzNkJIVkNjZlA4
    b2g4Z2JRV2JSeXlGS0piY29lTVJBelpjTVZTbnEyRjdobjB1OUhSbmpidVhvZGIwSwoycGJ4ekNJ
    eVBnMENnWUVBc0kxblhlWSs5ZkZCTVJHeEFLczFTOVhtNFFxZTlUMFNDS3NIVEF0VzJ5czF1ODFq
    CkoyMFFqRDc0TWYzalg3MXR5YlExeFpPT1BRcVVNT3IyQ0JFU1pKV0NVUWtrakNCdzRFeXBwaTdQ
    K09WVmR6bHIKdmZpSnk1NkJ2WW9jMlN0NHg1MzliMkdMWTM3bDVJdTE1cmg5bDdXYU1QczNCTWVZ
    YlZKZktLZUNGWGtDZ1lFQQp6NGpWRVgvMmtDVG5BalpRaEhPNEMzZHUwckgzeFNPMEhDMnhIbmJv
    TG42NC9qUkx4MjJLMTFaRGdIUlBVUVFqCk5SWm9rTWJ1aCtjNGJzMjVCUnUwb2lYRzhSN0hvZWVZ
    T0FCYzRFbHJDQjd0bzJCV1VCbWdMbTJPTkN3R29LaUIKaWJHZE9OUW03NEhsbXZDc3cxMFBuczV6
    Wnk0OU01YmkrYzN5ekhzSVpPa0NnWUIrSDJ3MTdIN0M4VDdITVhWbQpQUGZkSFRqSDNUeWVsOHdm
    eTJidFZyQXo5eVdtR0s1QUFta0o4b1VXazVibWJXRTlOTVB2a0RGQzZRMnAvbUFTCjZNL3pwT04v
    Z3c0bng1eGphSERYMEJuYUJVS3ZNL3hnWk5iT3E4YzN0YUJ4TXNBNGkyZUNpY2VHS2hpT1JUVlkK
    Y1cvQTFHRDFwd2s2ZjQwbVRjemhZeHdYRHc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
