name: Terraform Deploy commonservices

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - stage
          - prod
      application:
        description: 'Application'
        required: true
        default: 'stohrm1-0'
        type: choice
        options:
          - stohrm1-0   
      eksEnabled:
        description: 'Plan EKS'
        required: true
        default: 'false'
        type: boolean
      ec2Enabled:
        description: 'Plan EC2'
        required: true
        default: 'false'
        type: boolean
      ecrEnabled:
        description: 'Plan ECR'
        required: true
        default: 'false'
        type: boolean        
      efsEnabled:
        description: 'Plan EFS'
        required: true
        default: 'false'
        type: boolean           
      remoteProvisionerEnabled:
        description: 'Plan RemoteProvisioner'
        required: true
        default: 'false'
        type: boolean          
      terraformApply:
        description: 'Apply Terraform changes after Plan'
        required: true
        default: 'false'
        type: boolean             
env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  APPLICATION: ${{ github.event.inputs.application }}
  VPC_PLAN: ${{ github.event.inputs.vpcEnabled }} 
  EKS_PLAN: ${{ github.event.inputs.eksEnabled }} 
  EC2_PLAN: ${{ github.event.inputs.ec2Enabled }} 
  ECR_PLAN: ${{ github.event.inputs.ecrEnabled }} 
  EFS_PLAN: ${{ github.event.inputs.efsEnabled }}
  REMOTEPROVISIONER_PLAN: ${{ github.event.inputs.remoteProvisionerEnabled }}   
  TERRAFORM_APPLY: ${{ github.event.inputs.terraformApply }}  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2

    - name: Set environment variables
      run: |
        echo "ENVIRONMENT=${{ env.ENVIRONMENT }}" >> $GITHUB_ENV
        echo "APPLICATION=${{ env.APPLICATION }}" >> $GITHUB_ENV

    - name: Set AWS Access Key ID and Secret Access Key based on Environment
      id: set-aws-credentials
      run: |
        if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> $GITHUB_ENV
          echo "RDS_STOHRM_USERNAME=${{ secrets.RDSDEV_STOHRM_USERNAME }}" >> $GITHUB_ENV
          echo "RDS_STOHRM_PASSWORD=${{ secrets.RDSDEV_STOHRM_PASSWORD }}" >> $GITHUB_ENV           
        elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_QA }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}" >> $GITHUB_ENV
          echo "RDS_STOHRM_USERNAME=${{ secrets.RDSQA_STOHRM_USERNAME }}" >> $GITHUB_ENV
          echo "RDS_STOHRM_PASSWORD=${{ secrets.RDSQA_STOHRM_PASSWORD }}" >> $GITHUB_ENV  
        elif [ "${{ github.event.inputs.environment }}" == "stage" ]; then
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}" >> $GITHUB_ENV
          echo "RDS_STOHRM_USERNAME=${{ secrets.RDSSTAGE_STOHRM_USERNAME }}" >> $GITHUB_ENV
          echo "RDS_STOHRM_PASSWORD=${{ secrets.RDSSTAGE_STOHRM_PASSWORD }}" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
          echo "RDS_STOHRM_USERNAME=${{ secrets.RDSPROD_STOHRM_USERNAME }}" >> $GITHUB_ENV
          echo "RDS_STOHRM_PASSWORD=${{ secrets.RDSPROD_STOHRM_PASSWORD }}" >> $GITHUB_ENV
        else
          echo "Invalid environment!"
          exit 1
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Adjust as necessary for your region        
        
    - name: Initialize Terraform
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}
      run: terraform init
      
    - name: Create .tfvars file stohrm
      if: ${{ github.event.inputs.application == 'stohrm1-0' }}
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}
      run: |
        cat <<EOF > runtime-variables.tfvars
        rds_db_username = ["${{ env.RDS_STOHRM_USERNAME }}"]
        rds_db_password = ["${{ env.RDS_STOHRM_PASSWORD }}"]
        aws_access_key_id = "${{ env.AWS_ACCESS_KEY_ID }}"
        aws_secret_access_key = "${{ env.AWS_SECRET_ACCESS_KEY }}"
        github_username = "${{ secrets.GITHB_USERNAME }}"
        github_password = "${{ secrets.GITHB_TOKEN }}"
        EOF
  
    - name: Initialize and plan Terraform VPC
      if: env.VPC_PLAN == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/vpc
      run: |
        terraform init
        terraform plan -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars"
        
    - name: Initialize and plan Terraform EKS
      if: env.EKS_PLAN == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/eks
      run: |
        terraform init
        terraform plan -var-file="runtime-variables.tfvars" -var-file="${{ env.ENVIRONMENT }}-terraform.tfvars"
        
    - name: Initialize and plan Terraform EC2
      if: env.EC2_PLAN == 'true' 
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/ec2
      run: |
        terraform init
        terraform plan -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars"
        
    - name: Initialize and plan Terraform ECR
      if: env.ECR_PLAN == 'true' 
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/ecr
      run: |
        terraform init
        terraform plan -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars"

    - name: Initialize and plan Terraform EFS
      if: env.EFS_PLAN == 'true' 
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/efs
      run: |
        terraform init
        terraform plan -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars"
                      
    - name: Initialize and plan Terraform RemoteProvisioner
      if: env.REMOTEPROVISIONER_PLAN == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/remoteprovisioner
      run: |
        terraform init
        terraform plan -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars"

    - name: Apply Terraform VPC
      if: env.VPC_APPLY == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/vpc
      run: terraform apply -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars" -auto-approve
      
    - name: Apply Terraform eks
      if: env.EKS_APPLY == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/eks
      run: terraform apply -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars" -auto-approve
      
    - name: Apply Terraform ec2
      if: env.EC2_APPLY == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/ec2
      run: terraform apply -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars" -auto-approve

    - name: Apply Terraform ecr
      if: env.ECR_APPLY == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/ecr
      run: terraform apply -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars" -auto-approve

    - name: Apply Terraform efs
      if: env.EFS_APPLY == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/efs
      run: terraform apply -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars" -auto-approve

    - name: Apply Terraform remoteprovisioner
      if: env.REMOTEPROVISIONER_APPLY == 'true'
      working-directory: ./terraform_infra_aws/applications/${{ env.APPLICATION }}/environments/${{ env.ENVIRONMENT }}/remoteprovisioner
      run: terraform apply -var-file="../runtime-variables.tfvars" -var-file="../${{ env.ENVIRONMENT }}-terraform.tfvars" -auto-approve
